# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod ‘Firebase/Messaging’
pod ‘Firebase/Crash’


target 'KOYOBUSNAVI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod ‘Firebase/Messaging’

  # Pods for KOYOBUSNAVI

  target 'KOYOBUSNAVITests' do
    inherit! :search_paths
    # Pods for testing
	pod ‘Firebase/Messaging’
  end

  target 'KOYOBUSNAVIUITests' do
    inherit! :search_paths
    # Pods for testing
	pod ‘Firebase/Messaging’
  end
end
